# This is a basic workflow to help you get started with Actions
# Building Envoy with the CI Docker image
# !Building Envoy with Remote Execution
# !Building Envoy with Docker sandbox

name: Envoy(Ubuntu Docker Image)

# Controls when the workflow will run
on:
  # schedule:
  #   - cron:  '0 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          repository: envoyproxy/envoy
          path: .
      - name: Get Repo Sha
        id: get-sha
        run: |
          echo "::set-output name=sha::$(git rev-list --max-count=1 origin/main)"
        shell: bash
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! github.sha=${{ steps.get-sha.outputs.sha }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
            ~/build
          key: ${{ runner.os }}-docker-${{ steps.get-sha.outputs.sha }}
      
      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          ENVOY_DOCKER_BUILD_DIR=~/build
          ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only'
      - name: 'Tar artifacts'
        run: |
          ls -l ~/build/envoy/source/exe
          tar -czvf envoy.tar.gz ~/build/envoy/source/exe/*
      - uses: actions/upload-artifact@v2
        with:
          name: envoy_bin
          path: ./envoy.tar.gz
