# This is a basic workflow to help you get started with Actions
# Building Mobile Envoy with Docker sandbox

name: Envoy Mobile CI - Android (Docker sandbox)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
       # http://man7.org/linux/man-pages/man1/date.1.html
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-envoy-mobile-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/README.md') }}
      
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          repository: envoyproxy/envoy-mobile
          submodules: true
          path: src
      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
          sudo chmod +x /usr/local/bin/bazel
          # tools
          sudo apt-get install -y libtool cmake automake autoconf make ninja-build curl unzip virtualenv python python3-pip
      - name: Build
        run:  |
          cd src
          bazel build android_dist --config=release-android --fat_apk_cpu=x86,armeabi-v7a,arm64-v8a
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: envoy.aar
          path: |
            src/dist/envoy.aar
