# build examples
name: proxy-wasm-go-sdk
on:
  # schedule:
  #   - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  build-examples:
    name: Build examples
    runs-on: ubuntu-latest
    container:
      image: tinygo/tinygo:0.18.0
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'

      - name: Install Make
        run: apt install make

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: tetratelabs/proxy-wasm-go-sdk
          # submodules: true
      - name: Get Repo Sha
        id: get-sha
        run: |
          echo "::set-output name=sha::$(git rev-list --max-count=1 origin/main)"
        shell: bash
      - name: Cache built examples
        uses: actions/cache@v2
        id: cache-built-examples
        with:
          path: examples
          key: examples-${{ hashFiles('examples/**', 'proxywasm/**') }}

      - name: Build examples
        if: steps.cache-built-examples.outputs.cache-hit != 'true'
        run: make build.examples

  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        image: [
          "envoyproxy/envoy-dev:latest", 
          "envoyproxy/envoy:v1.18.2", 
          "istio/proxyv2:1.9.6", 
          "istio/proxyv2:1.10.3",]
    name: E2E Test (${{ matrix.image }})
    needs: build-examples
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      options: --privileged
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'

      - name: Print Envoy version
        run: envoy --version

      - name: Install Make
        run: apt update && apt install make

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: tetratelabs/proxy-wasm-go-sdk

      - name: Fetch built examples
        uses: actions/cache@v2
        with:
          path: examples
          key: examples-${{ hashFiles('examples/**', 'proxywasm/**') }}

      - name: Run e2e test
        run: make test.e2e
        env:
          CGO_ENABLED: "0"
