# This is a basic workflow to help you get started with Actions
# !Building Envoy with the CI Docker image
# !Building Envoy with Remote Execution
# Building Envoy with Docker sandbox

name: Build Envoy CI (Ubuntu Docker sandbox)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          repository: envoyproxy/envoy
          path: .

      - name: Get Repo Sha
        id: get-sha
        run: |
          echo "::set-output name=sha::$(git rev-list --max-count=1 origin/main)"
        shell: bash
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! github.sha=${{ steps.get-sha.outputs.sha }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ steps.get-sha.outputs.sha }}
      
      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
          sudo chmod +x /usr/local/bin/bazel
          # tools
          sudo apt-get install -y libtool cmake automake autoconf make ninja-build curl unzip virtualenv python python3-pip
      - name: Build
        run:  |
          bazel build //source/exe:envoy-static --config=docker-clang
